# Generated by Django 5.1.7 on 2025-05-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_courseday_courseterm_rename_time_coursetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='course',
        ),
        migrations.RemoveField(
            model_name='program',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='short_code',
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='courseday',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
